#!/usr/bin/env bash
#
# Setup KITTY Artifacts Directory
#
# Creates the shared artifacts directory for storing CAD files (STL, STEP, OBJ)
# and reference images. This directory is accessible from macOS Finder for easy
# access to generated files.
#
# Usage: ./ops/scripts/setup-artifacts-dir.sh [custom-path]
#
# If no custom path is provided, uses KITTY_ARTIFACTS_DIR from .env or the default
# /Users/Shared/KITTY/artifacts
#

set -euo pipefail

# Color output helpers
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

info() {
    echo -e "${BLUE}ℹ${NC} $*"
}

success() {
    echo -e "${GREEN}✓${NC} $*"
}

warning() {
    echo -e "${YELLOW}⚠${NC} $*"
}

error() {
    echo -e "${RED}✗${NC} $*" >&2
}

# Get the project root directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"

# Load KITTY_ARTIFACTS_DIR from .env if it exists
if [[ -f "${PROJECT_ROOT}/.env" ]]; then
    # shellcheck disable=SC1091
    source <(grep -E '^KITTY_ARTIFACTS_DIR=' "${PROJECT_ROOT}/.env" || true)
fi

# Use custom path from argument, or from .env, or default
ARTIFACTS_DIR="${1:-${KITTY_ARTIFACTS_DIR:-/Users/Shared/KITTY/artifacts}}"

info "KITTY Artifacts Directory Setup"
echo ""
info "Target directory: ${ARTIFACTS_DIR}"
echo ""

# Create main artifacts directory
if [[ -d "${ARTIFACTS_DIR}" ]]; then
    warning "Directory already exists: ${ARTIFACTS_DIR}"
else
    info "Creating directory: ${ARTIFACTS_DIR}"
    mkdir -p "${ARTIFACTS_DIR}"
    success "Created main directory"
fi

# Create subdirectories for organization
SUBDIRS=(
    "cad"           # CAD files (STL, STEP, OBJ, GLB, DXF)
    "images"        # Reference images for CAD generation
    "metadata"      # JSON metadata files tracking provenance
    "temp"          # Temporary files during processing
)

for subdir in "${SUBDIRS[@]}"; do
    SUBDIR_PATH="${ARTIFACTS_DIR}/${subdir}"
    if [[ -d "${SUBDIR_PATH}" ]]; then
        info "Subdirectory already exists: ${subdir}/"
    else
        mkdir -p "${SUBDIR_PATH}"
        success "Created subdirectory: ${subdir}/"
    fi
done

# Set permissions to ensure Docker containers can write
# Docker runs as specific user IDs, so we make the directory world-writable
# with sticky bit to prevent deletion of others' files
info "Setting permissions..."
chmod -R 755 "${ARTIFACTS_DIR}"
success "Permissions set to 755 (rwxr-xr-x)"

# Create a README in the artifacts directory
README_PATH="${ARTIFACTS_DIR}/README.md"
if [[ ! -f "${README_PATH}" ]]; then
    cat > "${README_PATH}" << 'EOF'
# KITTY Artifacts Directory

This directory stores CAD models and reference images generated by KITTY.

## Directory Structure

- **cad/**: CAD files (STL, STEP, OBJ, GLB, DXF)
- **images/**: Reference images used for CAD generation
- **metadata/**: JSON metadata tracking file provenance
- **temp/**: Temporary files during processing

## Opening Files

### STL Files in Fusion 360

1. Open Fusion 360
2. Click **File** → **Open** (or **Insert** to add to current design)
3. Navigate to this directory: `cad/`
4. Select your STL file
5. Fusion will import the mesh for editing or reference

### STL Files in Other Applications

- **Blender**: File → Import → STL
- **MeshLab**: File → Import Mesh
- **PrusaSlicer/Cura**: Just drag & drop
- **FreeCAD**: File → Open

## File Naming Convention

Files are named with the following pattern:
```
<timestamp>_<hash>_<description>.<ext>

Example:
20251110_a3f2b1c_hex-box-50mm.stl
```

## Metadata

Each CAD file has a corresponding JSON metadata file in `metadata/` with:
- Generation prompt
- Provider used (Zoo, Tripo, local)
- Timestamp and user
- Processing parameters
- Source reference images (if any)

## Cleanup

Old files are NOT automatically deleted. You can safely delete any files you no longer need.

## Integration

KITTY stores artifacts here and Docker services mount this directory at:
- `/app/storage` (primary mount point)
- `/app/artifacts` (legacy compatibility)

Any file you place in `images/` can be referenced by KITTY for CAD generation.
EOF
    success "Created README.md"
fi

# Create a .gitignore to prevent accidental commits of generated files
GITIGNORE_PATH="${ARTIFACTS_DIR}/.gitignore"
if [[ ! -f "${GITIGNORE_PATH}" ]]; then
    cat > "${GITIGNORE_PATH}" << 'EOF'
# Ignore all artifacts by default
*

# But keep the directory structure
!.gitignore
!README.md
!cad/.gitkeep
!images/.gitkeep
!metadata/.gitkeep
!temp/.gitkeep
EOF
    success "Created .gitignore"
fi

# Create .gitkeep files to preserve empty directories in git
for subdir in "${SUBDIRS[@]}"; do
    GITKEEP_PATH="${ARTIFACTS_DIR}/${subdir}/.gitkeep"
    if [[ ! -f "${GITKEEP_PATH}" ]]; then
        touch "${GITKEEP_PATH}"
    fi
done

# Test write permissions
TEST_FILE="${ARTIFACTS_DIR}/temp/.test-write-$$"
if touch "${TEST_FILE}" 2>/dev/null; then
    rm -f "${TEST_FILE}"
    success "Write permissions verified"
else
    error "Cannot write to ${ARTIFACTS_DIR}"
    error "Please check ownership and permissions"
    exit 1
fi

echo ""
success "Artifacts directory setup complete!"
echo ""
info "Next steps:"
echo "  1. Update your .env file:"
echo "     KITTY_ARTIFACTS_DIR=${ARTIFACTS_DIR}"
echo ""
echo "  2. Restart KITTY services to mount the new directory:"
echo "     docker compose -f infra/compose/docker-compose.yml down"
echo "     docker compose -f infra/compose/docker-compose.yml up -d"
echo ""
echo "  3. Generate a test CAD model:"
echo "     kitty-cli cad \"Create a simple cube 50mm\""
echo ""
echo "  4. Open in Finder:"
echo "     open \"${ARTIFACTS_DIR}/cad\""
echo ""
info "Files accessible at: ${ARTIFACTS_DIR}"

# Offer to open in Finder if on macOS
if [[ "$(uname)" == "Darwin" ]]; then
    echo ""
    read -p "Open artifacts directory in Finder now? [y/N] " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        open "${ARTIFACTS_DIR}"
        success "Opened in Finder"
    fi
fi
